### ISSUE TITLE
Documentation Hub

### ISSUE THREAD

**Issue by lkngtn** [1Hive/ideas#1]
Do we want to create and maintain a documentation hub? If so what is the initial scope and audience?

**Comment by lkngtn** [comment]
Some things to consider:
- Documenting our processes and how members engage with the various applications
- Documenting how the social/organizational expectations of members and various roles within the organization. 

- Documenting the applications we are using and how they can be installed (for the benefit of other organizations)      
- Also document other Aragon apps which we are not currently using because they may not be discovered otherwise. if we do this perhaps we should maintain our own apm repo and then make sure anything that is submitted to the repo has consistent documentation?

**Comment by yeqbfgxjiq** [comment]
[🦕](https://docusaurus.io)?

**Comment by lkngtn** [comment]
Docusaurus seems like a good choice for this. I think we could also use it to host a blog if we want?

**Comment by yeqbfgxjiq** [comment]
Yeah blogs are built in. You just write in markdown and Docusaurus makes it look pretty. Really easy to edit from a web admin perspective too because you just create a new markdown file in the `blog` folder and it gets added :)

**Comment by 0xGabi** [comment]
>Also document other Aragon apps which we are not currently using because they may not be discovered otherwise. if we do this perhaps we should maintain our own apm repo and then make sure anything that is submitted to the repo has consistent documentation?

Good idea!

**Comment by yeqbfgxjiq** [comment]
[We have a blog!](https://1hive.github.io/mvp/blog/) It needs to be filled with content, but it's definitely there. Also, [we have docs](https://1hive.github.io/mvp/docs/welcome) (that also need better content). [Moved this Issue into the MVP](https://github.com/1Hive/mvp/issues/11) so that we can build it into the site and ship it :)

Unless anyone objects is it safe to close this Issue here and engage with it on the MVP?

**Comment by yeqbfgxjiq** [comment]
Are we good to close this issue now that the website is launched and we have an open issue there exploring how to best configure the docs?
- https://github.com/1Hive/website/issues/15
