### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#11]
- thou shalt not criticize or condemn unless thou hast a better solution
- if thou hast a better solution, thou shal create an Issue or submit a PR
- if thou seeith a security flaw, thou shalt sound the alarm
- build first, ask questions later
- but if you're building on someone else's work, fork or submit a PR to make sure you're not breaking something important

**Comment by lkngtn** [comment]
I think we could expand on this and add the code of conduct into the onboarding docs. I'm not sure how I feel about these specifically though:

> thou shalt not criticize or condemn unless thou hast a better solution

I think allowing discussion and even criticism without being able to present a better solution is healthy. I see the motivation behind this, as there is clearly a line between constructive discussion and unproductive negativity. 

> build first, ask questions later

I think its also helpful to ask questions/discuss and try and reach consensus before building things (atleast sometimes). We all have limited bandwidth in terms of time and attention, and building as a group not only requires building but also reviewing. 

Overall I think I'm mostly aligned with these things, but feel like they may emphasize too much individual action and discourage collaboration/planning.

**Comment by yeqbfgxjiq** [comment]
This Issue was more meant to be a joke than anything, but seemed like it might be good to start a conversation around how we want to operate/communicate (because CoC's are all about communication) so I just threw it out there lol

> I think allowing discussion and even criticism without being able to present a better solution is healthy. I see the motivation behind this, as there is clearly a line between constructive discussion and unproductive negativity.

100% 

> I think its also helpful to ask questions/discuss and try and reach consensus before building things (atleast sometimes). We all have limited bandwidth in terms of time and attention, and building as a group not only requires building but also reviewing.

and yes I totally agree, but I meant more that design by committee kills brainstorming and innovation so it's better to try stuff than to perpetually seek perfection. Again, more meant to be a joke than anything, but worth a conversation non the less

 > Overall I think I'm mostly aligned with these things, but feel like they may emphasize too much individual action and discourage collaboration/planning.

Yeah totally. My bad. I thought the "thou shalt" type speak would make it clear that these were half assed jokes/suggestions, but I should've emphasized that more clearly. The Grin community actually used to have a really cool an cool CoC/values page that was half funny half serious, but I see they've updated it to [something more professional](https://github.com/mimblewimble/grin#philosophy) :/ Anyways, was just starting this thread as a joke/conversation, but it's not meant to be taken too seriously :)
