### ISSUE TITLE
Liquid Democracy?

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#12]
Is Aragon making progress on liquid democracy (delegate/proxy voting) or would it be worth digging up the 1Hive version?
- https://github.com/1Hive/Hive-Democracy

**Comment by lkngtn** [comment]
https://forum.aragon.org/t/open-challenges-for-on-chain-liquid-democracy/161 

Has some good information on what the open challenges are... 

I think a simple proxy voting contract probably gets us a lot of the advantages of delegation, without introducing a lot of the complexity of full liquid democracy.
