### ISSUE TITLE
HNV Dashboard

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#17]
Dashboard showing participation rates and results for Hive Network Votes. 

Not sure what the best way to go about this is, but @light and @sohkai had some great ideas (that got buried) in the [Aragon dev chat](https://aragon.chat/channel/dev)

**Comment by lkngtn** [comment]
As we were discussing, being able to link participation in votes to specific addresses members/and show that on a dashboard could be really useful for a community which has some expectation of member participation. 

For 1hive:
- Would be great to track a rolling participation rate for each `Bee` holder, (number of votes participated in / total in the last 3 months). If this is lower than all the other members that is a sign to check-in with them and perhaps remove them. 
- Would be great to track how much honey is earned by addresses in a rolling period time from the bounties contract and from allocations. (eg only track honey which is earned and not honey which is purchased). Would give us a sense of contributive activity outside of voting. 

I think the idea of a voting specific dashboard is a bit less interesting, particularly for us... But I think a community activity/participation focused dashboard would be very useful for open source communities that are using an Aragon DAO.
