### ISSUE TITLE
 LR and QV Aragon Apps Suite

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#20]
There's a lot of interest in the blockchain world about [Liberal Radicalism](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3243656) and [Quadratic Voting](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2003531). While these models are very interesting, actually applying them is difficult. There are [many problems that need to be addressed](https://medium.com/@lkngtn/thoughts-on-liberal-radicalism-2c76eaa397ec) before these tools can be tested in the real world. 

Aragon is a platform that allows people to combine modular components into DAO protocols. This means that it would be possible to create applications that solve many of the problems introduced by LR and QV, and then combine them into a working DAO. This would be a fun and interesting challenge for 1Hive to take on.

The problems/applications that would be need to make this happen are:
- content curation
- sybil resistance
- more I'm not thinking of

**Comment by yeqbfgxjiq** [comment]
### Content Curation / Spam Reduction

There are tons of options for this:
- [Token Curated Registries](https://github.com/miguelmota/awesome-token-curated-registries)
- Prediction Markets
- [everything here](https://ethresear.ch/t/list-of-primitives-useful-for-using-cryptoeconomics-driven-internet-social-media-applications/3198)

**Comment by yeqbfgxjiq** [comment]
### Sybil Resistance

This one is a lot harder. There are 2 approaches I see, but I'm sure there's more:
- KYC type mechanisms
- a web of trust / reputation system to establish credibility

**Comment by yeqbfgxjiq** [comment]
### More Things 

This is a placeholder for the things I'm not thinking of atm :)

**Comment by lkngtn** [comment]
I like this idea, but I think we should prioritize solving the identity issue first. Thinking out loud, perhaps the following initiative should precede this:

**BeeID**
A re-usable KYC and uniqueness validation service which can be used to by organizations and developers. 

BeeID could be used to provide sybil resistance for user onboarding, quadratic voting, and quadratic finance apps.

**Comment by yeqbfgxjiq** [comment]
Yeah 100%. Identity is the foundation of all these things. Daonuts is actually working on LR/QV stuff tho because the identity layer is "verified" on the Reddit side. In the context of Daonuts adding a QV app that you can swap for the karma-cap app or whatever is rather trivial. For other DAOs tho, not so much...

I'm not a huge fan of KYC, as you can imagine lol. Isn't Autark working on Aragon identity integration with Aragon DAOs tho?

**Comment by lkngtn** [comment]
> I'm not a huge fan of KYC, as you can imagine lol. Isn't Autark working on Aragon identity integration with Aragon DAOs tho?

I don't love KYC either, but its probably the most pragmatic solution sybil resistant identity for most use cases. I'm a huge supporter of projects like brightid, and will continue to support them, but for something like CLR matching (where there is already a centralized entity which is providing funds) having a centralized identity provider is totally fine, probably more secure, and much easier to actually implement.

As far as im aware they are working on user profiles and integrating with 3box, but this doesn't really provide sybil resistance directly.  

Besides I wouldn't think of BeeID as an identity solution for Aragon DAOs, though Aragon DAOs/App developers could certainly use it. But rather as a general and public primitive for sybil-resistance.

**Comment by yeqbfgxjiq** [comment]
Yeah actually now that I think about it, initially I was triggered by the term "KYC" because I associate that with giving user identities to corporations who then sell it on data markets for profit. In this case tho, we'd actually just be verifying that a person in the community is able to participate in more interesting voting/signalling mechanisms. Essentially we're just linking usernames (like from Keybase or something) to Ethereum tokens (either adding them to a whitelist or minting them a membership token). 
Daonuts is doing something similar linking Reddit usernames to Ethereum addresses. More info on that [here](https://github.com/burrrata/daonuts-website/issues/9). Are you imagining something like that to authenticate users to the 1Hive sidechain or QV app/registry?
