### ISSUE TITLE
Tokens As Data Guide

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#23]
As lot of people coming from traditional backgrounds in the private equity or cooperative spaces seem to view tokens merely as magic internet money. This is just one side of the story. Tokens are really just ways to measure and manage a data point we want to track. That can be a currency, membership in an organization, reputation, or anything else. It would be great to have a post/guide explaining the wild world of tokens to people who might have only heard of bitcoin/ethereum in the context of market bubbles and trading.

**Comment by lkngtn** [comment]
Perhaps expanding on this section as a standalone guide on the token manager and different use cases makes sense: https://hack.aragon.org/docs/guides-custom-deploy#adding-a-token-and-token-manager-instance
