### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#24]
It seems like there are a lot of common questions/concerns regarding sustainable/funded open source. It would be great to address these on the website. This [HackerNews thread](https://news.ycombinator.com/item?id=19989684) is a great example of common questions/concerns.

**Comment by DISC30** [comment]
Nice! I agree with making products free/open source and have been wrestling with how to fund that while being fair to all the workers/contributors, and this model (for open source code) in combination with my CEO's idea of service fees (for added services) seems like a good balance.

**Comment by DISC30** [comment]
Edit: We're fully decentralized now! My (previously-known-as) CEO had the foresight to embrace the DAO structure, so everyone on our team is either a worker/contributor or a customer/investor now.
