### ISSUE TITLE
Collaboration & Credit Principles

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#25]
Inspired by Chris Olah's recent post "[Collaboration & Credit Principles](https://colah.github.io/posts/2019-05-Collaboration/index.html)". While the article is geared towards formal publishing in an academic/corporate setting, the heart of the matter is that open source and community collaboration requires trust and good will. Part of that involves giving credit where credit is due. 

At 1Hive, we care deeply about open source and community development. While contributions to GitHub repos can be checked and votes on DAOs are open to the public, I think we can do more. I'd like to propose that we start adding a "Contributions" section in the README of every repo stating who did what as well as any tools or prior work used to create whatever is in the repo. 

Please comment with thoughts/suggestions :)

**Comment by DISC30** [comment]
I propose just making it a habit to ask people permission to include, or giving them write permissions and having them directly write in, any ideas of theirs that you use. Obviously if you are using ideas from something you read, you would just include the link/attribution to it. 

And in case you find that the article you read turns out to be an independent discovery of an idea of a prior author that you didn't read, you should still acknowledge the earliest prior author.

**Comment by lkngtn** [comment]
> I'd like to propose that we start adding a "Contributions" section in the README of every repo stating who did what as well as any tools or prior work used to create whatever is in the repo.

I think there may be some tools which will automatically add a section to readme based on merged commits and other stats, I wouldn't be opposed to something like that. But unless we automate this I feel like it would be more of a pain then it is worth (the commit history already shows who has contributed and how).

**Comment by yeqbfgxjiq** [comment]
Yeah it could become a pain in the ass. Maybe it could be something that we do once whenever we publish an app to mainnet? It's really not that big of a deal, but I think that doing it A) allows people to look back on the work they did and B) it sets a precedent so that giving credit and being transparent is something that's built into the DNA of the community. It's a small thing, but I think it would be nice
