### ISSUE TITLE
ideas should be issues

### ISSUE THREAD

**Issue by lkngtn** [1Hive/ideas#29]
I'm finding the split between cryptoeconomics as files in this repo, and general issues a bit confusing. 

Is there any reason we shouldnt just use issues for all ideas and have a single uniform process?

**Comment by yeqbfgxjiq** [comment]
Yeah that's a good point. I think back in the day the thinking was that we could jam on the ideas and submit PRs and whatnot, but we're not doing that for V2 anymore so Issues are a much better fit.
