### ISSUE TITLE
Allocations: Conviction Voting

### ISSUE THREAD

**Issue by DISC30** [1Hive/ideas#33]
Why don't we use **conviction** voting to decide what projects/contributors to fund when and how much? 
And allow anyone to become a **member** (add wallet, track contributions on GitHub, earn HONEY, vote with HONEY on contributor funding, redeem HONEY from community vault)? 
And allow anyone to **invest** (purchase POLLEN from bonding curve, deduct a transaction fee toward community vault, vote with POLLEN on project funding, redeem POLLEN from bonding curve)?

This solves the problems of 
1) Curators and Reviewers disagreeing with each other
2) Allocations Admin (dictatorship)
3) A random person purchasing a bunch of HONEY and becoming a member and owning like all of the community vault
4) Since ["A Honey-based vote is required to add or remove someone from the curator or reviewer role"](https://1hive.org/contribute/projects-tasks) anyways, we might as well use Honey to vote for fund allocation directly instead of having middlemen.

**Comment by yeqbfgxjiq** [comment]
As mentioned on Keybase, we're currently implementing a minimum viable model. We just want something that works now, but even still we're stuck on Rinkeby and are waiting for various Aragon apps to get published to mainnet. In the future though, conviction voting and bonding curves could greatly enhance the 1Hive community.

**Comment by DISC30** [comment]
Gotcha. Looking into PoW/PoS/PoA/PoH/combined options so we'll be ready with the tech when it becomes available.
