### ISSUE TITLE
Wiki / Aragora Suite

### ISSUE THREAD

**Issue by lkngtn** [1Hive/ideas#45]
This idea was brought up by @sembrestels in keybase

- Docs or Wiki - For documents and agreements (in the future we can have another more specific app for Agreements)
- Proposals - already discussed here
- Blueprints - A DAO builder that can install apps, change permissions and mint/burn tokens in just one vote
- Connections - An app that connects a DAO with apps from other DAOs through permissions (probably using an agent underneath)

**Comment by sembrestels** [comment]
Ups, closing in favor of #46.
