### ISSUE TITLE
Aragon Labs Archives? 📦

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#6]
Diving into the Aragon archives and found this gem: [ALP02: Token-weighted Github Issue Prioritization #2](https://github.com/aragon/labs/issues/2). AFAIK there isn't a TCR to prioritize GitHub issues, not even in the TPS Projects app. <s>Is there another version of this that was shipped elsewhere, or</s>why was [this](https://github.com/skmgoldin/tcr) not [turned into an Aragon app](https://github.com/aragonlabs/curation)? Would it be worth revisiting?

**Comment by yeqbfgxjiq** [comment]
Also, it seems like most of these [ideas/Issues](https://github.com/aragon/labs/issues) and repos on [Aragon Labs](https://github.com/aragonlabs) were really good. Being how this was almost a year ago, and the suite of Aragon apps is still fairly small, maybe it would be fun to revisit these?

We could even have challenges/bounties if the broader community wants to work on them?

**Comment by lkngtn** [comment]
I think reviewing some of them and creating "ideas" for them would be okay, but I also feel like we don't necessarily need to pre-populate or surface them too much, especially if there is not an immediate use-case that we want to unlock.

**Comment by lkngtn** [comment]
BTW as far as TCR goes, we did quite a bit of work trying to modularize the original TCR pattern, but found that most people that were interested in making TCRs were looking to build custom UIs. The organization specific use case for a TCR ended up being a bit different and is actually solved in a fairly general way with proposal agreements and the court. https://github.com/aragon/whitepaper/pull/22

**Comment by lkngtn** [comment]
I think this can probably be closed, looking through those issues I think we probably don't need to port anything over directly.
