### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/ideas#8]
Having a podcast with the objective of instruct peope on how to create their own DAO using Aragon apps. Aim for the following objectives:

1. Explain 1Hive mechanisms
2. Use the space to explore new models align with audience needs
3. Improve open source tools for colaboration of teams

**Comment by yeqbfgxjiq** [comment]
I support this. It would help us reach a larger audience and provide more ways for people to learn/engage if they can't always be reading or at their computers. I have no ability/desire to make a podcast myself, but I totally support the idea and think it would be a great addition to the community :)

**Comment by yeqbfgxjiq** [comment]
Moved this to the Communication repo so that it can become part of the outreach/marketing plan :)
- https://github.com/1Hive/communication/issues/3
