### ISSUE TITLE
Apiary: bonding curve onboarding

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/ideas#9]
The Aragon Black team wants people to sign up to test drive the new bonding curve. Have we done that yet?
- https://forum.aragon.org/t/apiary-curve-bonding-onboarding/908

**Comment by lkngtn** [comment]
I haven't signed up yet, as we haven't really identified exactly how we want to approach using the bonding curve in 1hive, and we also have a pretty open line of communication with them and will be able to test without necessarily requiring their guidance.
